apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: janxyz
resources:
- deployment.yaml
- service.yaml
images:
- name: walking-in-bevy-server
  newName: ghcr.io/jan-xyz/walking-in-bevy-server
  newTag: v0.0.2
