[package]
name = "walking-in-bevy-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
bevy.workspace = true
bevy-tnua.workspace = true
leafwing-input-manager.workspace = true
lightyear = { workspace = true, features = ["netcode", "udp"] }
walking-in-bevy-shared.workspace = true
